# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

design_cpp <- function(X, n1, a, max_tries) {
    .Call(`_rerand_design_cpp`, X, n1, a, max_tries)
}

get_quantile_cpp <- function(R2, K, p_a, alpha, n_sim) {
    .Call(`_rerand_get_quantile_cpp`, R2, K, p_a, alpha, n_sim)
}

