# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rem_core_cpp <- function(X, Y, n1, a, max_tries) {
    .Call(`_rerand_rem_core_cpp`, X, Y, n1, a, max_tries)
}

